version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    
    steps:
        - checkout
        - run: echo $CIRCLE_BUILD_URL
        - run: sudo apt-get install -y git wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
        - run: |
            	for apk_file in $(sudo find -type f -name "*.apk") ; do
                  echo $apk_file
                  package_name=$(sudo aapt2 dump $apk_file )
                  echo "$apk_file:$package_name"
              done

